This is a test for "Upgrade Axis2 to 1.7.0" - https://issues.apache.org/jira/browse/OFBIZ-6916
It's a security update. It also concerns OFBIZ-6755 but to not mix things it will be done later. So to not block this issue, the commons-httpclient-3.1 lib is moved from framework/service/lib to specialpurpose/passport/lib/ where it's still required (no code change in this commit, only libs update)

It's a test because I began this work on Windows and there the NTML Auth is expected https://axis.apache.org/axis2/java/core/docs/http-transport.html#preemptive_auth. So, on my machine, I get this error with testSOAPSimpleService and testSOAPService:

TestRunContainer              |W| [JUNIT (error)] - testSOAPSimpleService : org.ofbiz.service.GenericServiceException: Service [testSoapSimple] Failed (org/apache/commons/httpclient/NTCredentials)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/NTCredentials
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.createHTTPSender(CommonsHTTPTransportSender.java:414) ~[axis2-transport-http-1.7.0.jar:1.7.0]


Since I don't want to introduce more complexity at this stage I hope the basic Auth will be used in BuildBot and the tests will all pass. Else I will revert and do more work...

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk/framework/service@1732631 13f79535-47bb-0310-9956-ffa450edef68